collections:
 posts:
   output: true
   permalink: /projects/:year/:slug

_options:
  content:
    blockquote: true
    horizontalrule: true
    format: p h1 h2 h3 h4 h5 h6
    bold: true
    italic: true
    numberedlist: true
    bulletedlist: true
    code: true
    table: true
    right: right
    center: center
    left: left
    embed: true
    link: true
    undo: true
    redo: true
    underline: true
    strike: true


_snippets:
  image_grid:
    template: jekyll_liquid_include
    inline: false
    preview:
      text: 3 image gallery
    definitions:
      include_name: snippets/imgGallery3.html
      named_args:
        - editor_key: first-image
          type: string
        - editor_key: first-alt
          type: string
        - editor_key: second-image
          type: string
        - editor_key: second-alt
          type: string
        - editor_key: third-image
          type: string
        - editor_key: third-alt
          type: string
        - editor_key: image_size_ratio
          type: string

floating_image:
  template: jekyll_liquid_include
  inline: true
  preview:
    text: floating image
  definitions:
    include_name: snippets/image-float.html
    named_args:
      - editor_key: image
        type: string
      - editor_key: alt
        type: string
      - editor_key: float-direction
        type: string  


_editables:
  content:
    type: markdown
    options:
      styles: /editor.css
      blockquote: true
      horizontalrule: true
      format: p h1 h2 h3 h4 h5 h6
      bold: true
      italic: true
      numberedlist: true
      bulletedlist: true
      code: true
      table: true
      right: right
      center: center
      left: left
      embed: true
      link: true
      undo: true
      redo: true
      underline: true
      strike: true
      image: true
      snippet: true
  cascade: true