# Snippet definitions are generic variables that can be referenced in snippets
# In this case, we're defining the common set of tokens that are relevant to
# Jekyll/liquid tags. (This covers things like the `=` symbol between keys and values)
# You shouldn't need to change these.
_snippets_definitions:
  jekyll_liquid_format:
    root_value_delimiter: '='
    root_pair_delimiter:
      - ''
    array_boundary:
      start: '['
      end: ']'
    array_delimiter: ','
    string_boundary:
      - '"'
      - ''''
    forbidden_tokens:
      - '%}'
      - '-%}'
      - '}}'
      - ','
  Snippet templates create a reusable structure to reduce repetition in snippets.
# These are what you normally import in cloudcannon using _snippets_imports
# As an example of creating one, here is a basic template for defining snippets that are liquid includes.